apiVersion: v1
kind: ConfigMap
metadata:
  name: firecrawl-redis
  namespace: firecrawl
  labels:
    app: firecrawl
    config-type: redis
data:
  REDIS_URL: "redis://redis-service.firecrawl.svc.cluster.local:6379"
  REDIS_RATE_LIMIT_URL: "redis://redis-service.firecrawl.svc.cluster.local:6379"
